name: build-openopys
on: [push]
jobs:
  calculate-coverage-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
          
      - name: Install testing packages
        run: pip install -r test_requirements.txt

      - name: Add plugin to annotate failures
        run: pip install pytest-github-actions-annotate-failures
      
      - name: Calculate coverage
        run: pytest --cov=src test_openopys.py

